#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Maratón Linuxero

# Short bio or description (displayed in the header)
description: Proyecto colaborativo de emisiones en directo a través de Software Libre

# URL of your avatar or profile pic (you could use your GitLab profile pic)
avatar: /media/logoMaratonLinuxero.png

# If you're hosting your site at a Project repository on GitLab Pages
# (http://yourusername.gitlab.io/repository-name)
# and NOT your User repository (http://yourusername.gitlab.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: https://maratonlinuxero.org
stream-base-url: https://emision.maratonlinuxero.org:8443/

# Enter your Isso URL to enable commenting on posts
isso: 

# Enter url and site-id to track visits
piwik:
  url: 
  site-id: 

# La cuenta atrás solo se activará si se escriben todos los valores
# fecha-hora está en horario español peninsular (UTC+2)
countdown:
  format: Quedan %-D día%!D, %-H hora%!H y %-M minuto%!M
  date:
    start: 2017-12-03 15:00
    end: 2017-12-03 19:00
  msg:
    start: Maratón Linuxero 1.2 ya ha comenzado. ¡Únete a la fiesta!
    end: Maratón Linuxero 1.2 ya ha terminado. ¡Gracias por participar!

# Video width and height
video:
  width: 560
  height: 315

# Metadata and links
gitlab: maratonlinuxero
telegram:
  group: maratonlinuxero
  channel: maraton_linuxero
mastodon:
  name: maratonlinuxero@mastodon.social
  url: https://mastodon.social/@maratonlinuxero
twitter: maratonlinuxero
facebook:
email: maratonlinuxero@disroot.org
youtube: https://www.youtube.com/maratonlinuxero
feed:
  path: /feed
  category:
    main: Technology
    sub1: Linux
  explicit: no
  summary: Sesiones del Maratón Linuxero
  subtitle: Los audios del Maratón Linuxero
archiveorg: maratonlinuxero
android: /MaratonLinuxero-1.3.apk

#
# You don't need to change any of the configuration flags below
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins_dir:
  - jekyll-sitemap
  - jekyll-feed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
