#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Maratón Linuxero

# Short bio or description (displayed in the header)
description: El 3 de septiembre, 9 horas de directos podcasteros sobre software libre. 

# URL of your avatar or profile pic (you could use your GitLab profile pic)
avatar: /media/logoMaratonLinuxero.png

# If you're hosting your site at a Project repository on GitLab Pages
# (http://yourusername.gitlab.io/repository-name)
# and NOT your User repository (http://yourusername.gitlab.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: /

# Enter your Isso URL to enable commenting on posts
isso: 

# Enter url and site-id to track visits
piwik:
  url: 
  site-id: 

# Activar la cuenta atrás asignando el valor true a activo, desactivarla asignando el valor false
countdown:
  activo: true
  formato: Quedan %-D día%!D, %-H hora%!H y %-M minuto%!M
  fecha_y_hora: 2017-09-03 15:00
  mensaje: Maratón Linuxero ya ha comenzado. ¡Únete a la fiesta!

# Video width and height
video:
  width: 560
  height: 315

# Metadata and links
gitlab: maratonlinuxero
telegram:
  group: maratonlinuxero
  channel: maraton_linuxero
mastodon: https://mastodon.social/@maratonlinuxero
mastodon_ref: maratonlinuxero@mastodon.social
twitter: maratonlinuxero
facebook:
email: maratonlinuxero@disroot.org
youtube: https://www.youtube.com/maratonlinuxero
radio: http://www.radiomaraton.ml
rss: /feed.xml
archiveorg: maratonlinuxero
android: /Maraton-Linuxero_1.3.apk

# Podcast Feed Settings
podcast-url: /
podcast-album-art: /media/logoMaratonLinuxero.png
podcast-title: Sesiones del Maratón Linuxero
podcast-owner: Maratón Linuxero
podcast-category: Technology
podcast-subcategory-one: Linux
podcast-explicit: no
podcast-author: Podcasteros Linuxeros
podcast-description: Los audios del Maratón Linuxero
podcast-summary: Los audios del Maratón Linuxero
podcast-subtitle: Los audios del Maratón Linuxero

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins_dir:
  - jekyll-sitemap
  - jekyll-feed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
